# Site Settings
title: My Resume
url: 'http://cjteodorski.us'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Chris Teodorski
tagline: Enterprise Cybersecurity
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Cybersecurity/Information security professional and CISSP with extensive experience providing defensive security
and proactive protection of Fortune 100 and government cloud-based and physical infrastructures'

#sidebar links
email: chris.teodorski@gmail.com
phone: (575) 208-4847
website:  #do not add http://
linkedin: linkedin.com/in/christeodorski
github: cteodorski
twitter: '@can0beans'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-111016934-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
